name: MLops CI

on:
  workflow_dispatch: {}

jobs:
  e2e_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'
        
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      
      - name: Run Data Processing Task  
        run: | 
          python src/data/run_processing.py \
            --input data/raw/house_data.csv  \
            --output data/processed/cleaned_house_data.csv
      
      - name: Run Feature Engineering task 
        run: | 
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output  data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl

      - name: Set up MLflow
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5000:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db
        
      - name: Wait for MLflow to start
        run: |
          for i in {1..10}; do
            curl -f http://localhost:5000/ || sleep 5;
          done

      - name: Train the model
        run: | 
          python src/models/train_model.py \
            --config configs/model_config.yaml  \
            --data data/processed/featured_house_data.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5000
      
      - name: Clean up MLflow
        run: |
          docker stop mlflow-server || true
          docker rm mlflow-server || true


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest
